wandb_version: 1

image_size:
  desc: null
  value:
  - 512
  - 512
embed_dim:
  desc: null
  value: 96
decoder_depth:
  desc: null
  value: 2
decoder_n_head:
  desc: null
  value:
  - 48
  - 24
  - 12
  - 6
decoder_window_size:
  desc: null
  value:
  - 4
  - 4
  - 8
  - 8
project_path:
  desc: null
  value: /raid/home/rizwank/courses/DLCV/Project
pascal_path:
  desc: null
  value: /raid/home/rizwank/courses/DLCV/Project/PASCAL_MT
train_batch_size:
  desc: null
  value: 10
val_batch_size:
  desc: null
  value: 32
num_workers_data:
  desc: null
  value: 2
ignore_index:
  desc: null
  value: 255
epochs:
  desc: null
  value: 50
warmup_steps:
  desc: null
  value: 2000
val_interval:
  desc: null
  value: 100
save_interval:
  desc: null
  value: 500
resume_training:
  desc: null
  value: false
wandb_project:
  desc: null
  value: encoder-decoder-dlcv
wandb_run_name:
  desc: null
  value: test-2
local_rank:
  desc: null
  value: 0
global_rank:
  desc: null
  value: 0
world_size:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.39.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711020740.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.16.4
      6: 4.39.0.dev0
      8:
      - 5
      13: linux-x86_64
